version: '2'
services:
    build:
        image: gcc:7.2.0
        network_mode: bridge
        volumes:
            - .:/code
        command: "bash -c 'cd /code; make; ./colReplacer'"
        tty: true

    clean:
        image: gcc:7.2.0
        network_mode: bridge
        volumes:
            - .:/code
        command: "bash -c 'cd /code; make clean'"
        tty: true

    test:
        image: gcc:7.2.0
        network_mode: bridge
        volumes:
            - .:/code
        command: "bash -c 'cd /code; make test; ./testColReplacer'"
        tty: true
